### PR TITLE
Traffic Chart spacing and ticks fix

### PR DESCRIPTION
**Pull request by stefaweb**
For testing.

I got this.

With maxTicksLimit + code (use 10 currently)
capture d ecran 2017-06-28 a 17 39 32

without
capture d ecran 2017-06-28 a 17 36 46

### CODE REVIEW

**Comment by Skywalker-11** [comment]
As soon as you show a tooltip the ticks disappear

**Comment by stefaweb** [comment]
Greeuuuuuu!

**Comment by stefaweb** [comment]
Found a new version of the function but no change.

capture d ecran 2017-06-28 a 19 21 38

**Comment by stefaweb** [comment]
The problem is when we move the mouse over a point.

capture d ecran 2017-06-28 a 20 08 02

**Comment by stefaweb** [comment]
Closing. @Skywalker-11's function  better than this one.

**Pull request closed without merging**
