### PR TITLE
Fix message ops add id in wrong scope

### LINKED ISSUE #722: SA Learning and Releasing not working in detail.php
When I try to SA learn or release a message, nothing happens when I press the Submit button.
The same page is shown but no information text if the action was successful.
The message is also not released.

The actions are working in rep_message_ops.php under Reports --> Message Actions

This worked before the upgrade to 3.0.1.9.

### PR DESCRIPTION
**Pull request by shawniverson**
Fixes #722

### CODE REVIEW

**Comment by stefaweb** [comment]
1.2.1.1...     🙃

**Comment by shawniverson** [comment]
Yeah, this looks a a very recent regression from the code refractoring stuff....

**Comment by endelwar** [comment]
doh! didn't test this before packaging 1.2.1 :(

**Comment by endelwar** [comment]
We need a checklist for all tests to be done before releasing, hopefully replacing it with phpunit tests

**Pull request merged**
