### PR TITLE
Movexaxislabel

### PR DESCRIPTION
**Pull request by Skywalker-11**

### CODE REVIEW

**Comment by Skywalker-11** [comment]
Just to clarify in Chart.js and Char.min.js only two `/ ` changed to `*`. Not sure why git thinks that other stuff also changed

**Comment by stefaweb** [comment]
Do you plan to remove lib/jpgraph and images/cache ?

**Comment by stefaweb** [comment]
> Just to clarify in Chart.js and Char.min.js only two / changed to *. Not sure why git thinks that other stuff also changed

Seems the files are full of TAB.

**Comment by Skywalker-11** [comment]
> Seems the files are full of TAB.

But why does git think that the tabs changed? I don't get that  :confused:

**Comment by endelwar** [comment]
> Not sure why git thinks that other stuff also changed

I think that is your ide, that (correctly :wink:) convert tabs to spaces, to see the relevant edits just add a `?w=1` at the end of compare url (https://github.com/mailwatch/MailWatch/pull/837/files?w=1)

**Comment by stefaweb** [comment]
I've done a copy/paste and the soft said "Do you want to convert TAB with SPACE?".

**Comment by Skywalker-11** [comment]
@endelwar are you sure? github shows that in both versions it is a mix of tabs space. Also nano usually does not change it :unamused:

**Comment by endelwar** [comment]
a `set tabstospaces` in .nanorc?

**Comment by Skywalker-11** [comment]
With old vi its working...

**Comment by Skywalker-11** [comment]
@stefaweb yes plan is to remove jpgraph and the cache folder but rep_mcp_score_dist.php still uses this and I haven't changed that yet

**Pull request merged**
