### PR TITLE
Fix type mismatch in sa rule hits report

### PR DESCRIPTION
**Pull request by shawniverson**
Fixes issue where this if block is always true.

### CODE REVIEW

**Comment by stefaweb** [comment]
And this one?

```
rep_mcp_rule_hits.php:        if ($row->ismcp !== 0) {
```

**Comment by shawniverson** [comment]
Good catch, updating PR

**Comment by stefaweb** [comment]
I've found these but not sure its related.

```
msrule.php:    if ($FilePath === false || (strpos($FilePath, $MailscannerEtcDir) !== 0 && strpos($FilePath, $MailscannerRepDir) !== 0)) {
password_reset.php:            if ($result->num_rows !== 1) {
password_reset.php:                if ($result->num_rows !== 1) {
```

**Comment by shawniverson** [comment]
Those are ok.  They return as numeric in those cases.

**Pull request merged**
