### PR TITLE
optional config parameter to define the chart interval

### PR DESCRIPTION
**Pull request by Skywalker-11**

### CODE REVIEW

**Comment by stefaweb** [comment]
Do we need to translate this in graphgenerator.inc.php?

`throw new \Exception('timeInterval or timeScale not set');`

**Comment by Skywalker-11** [comment]
Exception shouldn't be thrown normally. It is just a reminder for devs when they are trying to use that function 😄

**Comment by stefaweb** [comment]
Ok.  😁

Think to center top legends.

**Comment by Skywalker-11** [comment]
The Legend alignment is tricky because the language strings have different lengths and this is also done by chart.js. Don't realy want to mess around with that code too much.

**Comment by stefaweb** [comment]
No problem if source of problem. ;)

**Pull request merged**
