### PR TITLE
New sendmail queue code

### PR DESCRIPTION
**Pull request by stefaweb**
Do not merge.

Use direct `sendmail -bp` command to print Sendmail queue in GUI instead of SQL query.

Dont' forget to place the sudo file "mailwatch" in /etc/sudoers.d/.

To be tested by Sendmail user.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/mailwatch/656)

### CODE REVIEW

**Comment by stefaweb** [comment]
If the code is ok, I will add constants in conf.php for `/usr/sbin/sendmail -bp -OQueueDirectory` and modify /etc/sudoers.d/.

**Comment by endelwar** [comment]
this need review by a sendmail user before merging

**Comment by stefaweb** [comment]
@endelwar 

What we do for this? We merge and wait if someone say its not working?

**Comment by Fonant** [comment]
Sorry, the change only seems to affect a distributed MailWatch setup, which I don't have.

**Comment by stefaweb** [comment]
Oops, it seems that I forgot to activate the right lines just below.

**Comment by Skywalker-11** [comment]
@stefaweb You left the merge markers

**Comment by stefaweb** [comment]
@Skywalker-11 
Done.

**Pull request merged**
